name: Upload Chromium build to Releases

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install npm dependencies
        run: npm ci

      - name: Build the extension
        run: npm run build:chromium

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/liveworksheets-solver*

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          path: packages/liveworksheets-solver*
